### ISSUE TITLE
Unwanted animation side effect within ZStack & NavigationView

### ISSUE THREAD

**Issue by mlohr** [AlexRoar/MorphingShapes#3]
When a MorphingCircle is embedded within a NavigationView (or Stack) and a ZStack its position is animated as well. Either from top left or bottom. This "moving-animation" is an unwanted side effect. In sample code below, in the first few seconds the shape will move upwards until it reaches the centre:

```
NavigationView {
    ZStack {
        MorphingCircle(outlineColor: .orange, outlineWidth: 10.0)
    }
}
```

Something you can fix @AlexRoar ?

**Comment by alexdremov** [comment]
It is unrelated to MorphingShape implementation. You are probably using `.animation()` incorrectly. Share a complete code example, please

**Comment by mlohr** [comment]
Well above is the sample code where I don't use animation. IMHO it's the `.animation()` within the package. Just try this code in your preview and you see the shape is (in the beginning) moving upwards. But only if it is also within a ZStack. But for my use case I need this setup (Navigation/ZStack) and there it somehow moves from top left corner to center.

In below code of the package if I uncomment the first update() I do NOT have the unwanted movement animation effect, but then the shape is at first not visible and pops in a second later at the right place....

```
            .onAppear {
                update()   // try commenting this out with above example preview code
                timer = Timer.scheduledTimer(withTimeInterval: duration / secting, repeats: true) { timer in
                    update()
                    onAnimation = true
                }

```

**Comment by mlohr** [comment]
In the mean time I am investigating if replacing NavigationStack with your PathPresenter library can resolve my unwanted movement animation issue....

**Comment by alexdremov** [comment]
I'll try to reproduce the issue later this day and will write to you about my findings!

**Comment by mlohr** [comment]
So I have refactored my code using your PathPresenter library and now I don't have an issue. So I am okay to close it.

**Comment by mlohr** [comment]
Workaround is to uses PathPresenter
